---
title: "UF - Morrison Lab Piney Point Results"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

Analysis from NSF RAPID project on tracking the effects of Piney Point discharge on Tampa Bay. Sites throughout Tampa Bay and St. Joseph Sound were sampled at minimum every two weeks. 

```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(cowplot)
library(knitr)
library(ggtext)


knitr::opts_chunk$set(echo = TRUE)


```

## Bulk Particulate Organic Matter (POM)
```{r, include=FALSE, echo=FALSE}
#raw_POM<-readxl::read_excel("../../Data/UF_SIL/Full_PP_GFF_data.xlsx", sheet = 1)

raw_POM<-read.csv("./Data/SPM_Frontiers.csv")

noNA_date<-raw_POM[!is.na(raw_POM$Date), ]  
noNA_date$`wt %N`<-as.numeric(noNA_date$`wt..N`)
noNA_date$`wt %C`<-as.numeric(noNA_date$`wt..C`)
noNA_date<-mutate(noNA_date, CN=`wt..C`/`wt..N`)
noNA_date$Date<-mdy(noNA_date$Date)

noNA_noBlank<-filter(noNA_date, Location!="Blank")

noNA_onlysites<-filter(noNA_date, Location==("Piney Point")
                       |Location==("Bishop Harbor")
                       |Location==("Joe Bay")
                       |Location==("St Joseph Sound"))


```

```{r, echo=FALSE, warning=FALSE}

#generate C, N, C:N plot
C<-ggplot(noNA_onlysites, aes(Date, `wt %C`))+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+ #date of tropical storm Elsa
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.01)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.01)+ #week of Jun 13 to July 18th reported as "high" k brevis from Beck et al., 2022, use dates
  geom_point()+
  geom_line()+
  facet_wrap(.~Location)+
  theme_cowplot(font_size = 8)+
   panel_border(color="black")+
  ggtitle("Total carbon")+
  ylab("Total carbon (%)")+
   xlab("")+
  theme(text = element_text(size = 14), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1)
        )  
  

N<-ggplot(noNA_onlysites, aes(Date, `wt %N`))+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+ #date of tropical storm Elsa
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.01)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.01)+ #week of Jun 13 to July 18th reported as "high" k brevis from Beck et al., 2022, use dates
  geom_point()+
   geom_line()+
  facet_wrap(.~Location)+
  theme_cowplot(font_size = 8)+
   panel_border(color="black")+
  ggtitle("Total nitrogen")+
  ylab("Total nitrogen (%)")+
   xlab("")+
  theme(text = element_text(size = 14), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1)
        )  

CN<-ggplot(noNA_onlysites, aes(Date, CN))+
    geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+ #date of tropical storm Elsa
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.01)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.01)+ #week of Jun 13 to July 18th reported as "high" k brevis from Beck et al., 2022, use dates
  geom_point()+
  geom_line()+
  facet_wrap(.~Location)+
  theme_cowplot(font_size = 8)+
   panel_border(color="black")+
  ggtitle("Carbon : Nitrogen")+
  ylab("C:N")+
  xlab("")+
  theme(text = element_text(size = 14), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1)
        )  


POM_plot<-plot_grid(C, N, CN, labels=c("A", "B", "C"))

ggsave("./Figures/Frontiers_2022/2022_12_13_POM_all.png", POM_plot, width=10, height=8)

```

```{r, echo=FALSE, warning=FALSE}

noNA_onlysites$`d15N..permil..vs.AIR.)`<-as.numeric(noNA_onlysites$`d15N..permil..vs.AIR.`)

noNA_onlysites_summary<-noNA_onlysites %>% 
  group_by(Location, month_year) %>% 
  summarize_at(c("d15N..permil..vs.AIR.", "d13C..permil..vs.VPDB.", 
                 "wt %C", "wt %N", "CN"),  list(mean = mean, sd = sd), na.rm=TRUE)

write.csv(noNA_onlysites_summary, "./Tables/Temp_tables/2023_POM_summary.csv")

noNA_onlysites_all_values<-noNA_onlysites %>% 
  select("Location", "Date", "d15N..permil..vs.AIR.", "d13C..permil..vs.VPDB.", 
                 "wt %C", "wt %N", "CN") %>%
  unique()
  
write.csv(noNA_onlysites_all_values, "./Tables/Temp_tables/2023_POM_all.csv")

```


```{r, echo=FALSE, warning=FALSE}
#test plot; not used in manuscript

all_data<-ggplot(noNA_date, aes(CN, `d13C..permil..vs.VPDB.`, color=Location)) +
  geom_point()

no_blank_plot<-ggplot(noNA_noBlank, aes(CN, `d13C..permil..vs.VPDB.`, color=Location)) +
  geom_rect(aes(ymin=-12, ymax=-25.5, xmin=4, xmax=6), color="cyan4", fill="cyan4", alpha=0.01)+ #bacteria
  geom_text(aes(x = 4.5, y = -14, label = "Bacteria"),size = 3, vjust = 0, hjust = 0, color = "black")+
  geom_rect(aes(ymin=-17, ymax=-9, xmin=20, xmax=30), color="gold3", fill="gold3", alpha=0.02)+ #C4 plants
  geom_text(aes(x = 24, y = -12, label = "C4 terrestrial plants"),size = 3, vjust = 0, hjust = 0, color = "black")+
  geom_rect(aes(ymin=-32, ymax=-21, xmin=13, xmax=30), color="gold3", fill="gold3", alpha=0.01)+ #C3 terrestrial plants
  geom_text(aes(x = 23, y = -26, label = "C3 terrestrial plants"),size = 3, vjust = 0, hjust = 0, color = "black")+
  geom_rect(aes(ymin=-33, ymax=-25, xmin=3, xmax=10), color="chartreuse4", fill="chartreuse4", alpha=0.01)+ #freshwater POC
  geom_text(aes(x = 5, y = -32, label = "Freshwater POC"),size = 3, vjust = 0, hjust = 0, color = "black")+
  geom_rect(aes(ymin=-24, ymax=-18, xmin=3, xmax=10), color="dodgerblue2", fill="dodgerblue2", alpha=0.01)+ #marine POC
  geom_text(aes(x = 9, y = -21, label = "Marine POC"),size = 3, vjust = 0, hjust = 0, color = "black")+
  geom_rect(aes(ymin=-30, ymax=-25, xmin=5, xmax=9), color="chartreuse4", fill="chartreuse4", alpha=0.05)+ #freshwater phyto
  geom_text(aes(x = 4, y = -26.5, label = "Freshwater phyto"),size = 3, vjust = 0, hjust = 0, color = "black")+
  geom_rect(aes(ymin=-16, ymax=-24.5, xmin=5, xmax=9), color="dodgerblue2", fill="dodgerblue2", alpha=0.05)+ #marine phyto
  geom_text(aes(x = 6.5, y = -17, label = "Marine phyto"),size = 3, vjust = 0, hjust = 0, color = "black")+
    geom_point(aes(color=`Location`), size=3)+
  theme_classic()+
  labs(y="*&delta;*<sup>13</sup>C (&permil; VPDB)", 
       x="C:N")+
  facet_wrap(.~month_year)+
  theme(
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown()
  )

no_blank_plot
```



### d13C for all locations and sampling dates for POM
```{r, echo=FALSE, warning=FALSE}

noNA_onlysites$`d13C..permil..vs.VPDB.`<-as.numeric(noNA_onlysites$`d13C..permil..vs.VPDB.`)

d13C<-ggplot(noNA_onlysites, aes(Date, `d13C..permil..vs.VPDB.`))+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+ #date of tropical storm Elsa
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.01)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.01)+ #week of Jun 13 to July 18th reported as "high" k brevis from Beck et al., 2022, use dates
  geom_point()+
  geom_line()+
  facet_wrap(.~Location)+
  theme_cowplot(font_size = 8)+
   panel_border(color="black")+
  geom_hline(yintercept = -14.01:-15.82, color="#00BA38")+
  labs(y="*&delta;*<sup>13</sup>C (&permil; vs.VPDB)", 
       x="Date", 
       title = "*&delta;*<sup>13</sup>C (&permil; vs.VPDB)")+
  theme(
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown(), 
    plot.title = element_markdown(),
    text = element_text(size = 14), 
    axis.text = element_text(size = 9), 
    axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1)
        )  

d13C


```



### d15N for all locations and sampling dates for POM
```{r, echo=FALSE, warning=FALSE}

noNA_onlysites$`d15N..permil..vs.AIR.`<-as.numeric(noNA_onlysites$`d15N..permil..vs.AIR.`)


d15N<-ggplot(noNA_onlysites, aes(Date, `d15N..permil..vs.AIR.`))+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+ #date of tropical storm Elsa
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.01)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.01)+ #week of Jun 13 to July 18th reported as "high" k brevis from Beck et al., 2022, use dates
  geom_point()+
  geom_line()+
  facet_wrap(.~Location)+
  theme_cowplot(font_size = 8)+
   panel_border(color="black")+
  labs(y="*&delta;*<sup>15</sup>N (&permil;vs.Air)", 
       x="Date", 
       title = "*&delta;*<sup>15</sup>N (&permil;vs. Air)")+
  theme(
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown(), 
    plot.title = element_markdown(),
    text = element_text(size = 14), 
    axis.text = element_text(size = 9), 
    axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1)
        )  

d15N

###Plot d13C and d15N together

iso_CN_plot<-plot_grid(d15N, d13C, labels=c("A", "B"), ncol=1)


ggsave("./Figures/Frontiers_2022/2022_12_12_iso_CN_plot.png", iso_CN_plot, width=10, height=8)

```

## Nutrient data
```{r, echo=FALSE, warning=FALSE, include=FALSE}

nutrients_raw<-read_excel("Data/PineyPoint_all_samples_w_data_simple.xlsx")

#filter just for the first year April 2021 to 2022
nutrients_year<-nutrients_raw[nutrients_raw$`Date of Sample collection` < "2022-05-01", ]



```

```{r, echo=FALSE, warning=FALSE, include=FALSE}


#set values that are below detection limit to NA
nutrients_year_filtered<-mutate(nutrients_year, `NH4N (mg/L)` = replace(`NH4N (mg/L)`, `NH4N flag`=="T"|`NH4N flag`=="T,J"|`NH4N flag`=="T, J"|`NH4N flag`=="T,Y"|`NH4N flag`=="T, Y" , NA), #want to use grepl but don't know how
         `NOx (mg/L)` = replace(`NOx (mg/L)`, `NOx flag`=="T"|`NOx flag`=="T,J"|`NOx flag`=="T, J"|`NOx flag`=="T,Y"|`NOx flag`=="T, Y" , NA),
         `OrthoP (ug/L)` = replace(`OrthoP (ug/L)`, `OrthoP flag`=="T"|`OrthoP flag`=="T,J"|`OrthoP flag`=="T, J"|`OrthoP flag`=="T,Y"|`OrthoP flag`=="T, Y" , NA),
         `TotalP (ug/L)` = replace(`TotalP (ug/L)`, `TotalP flag`=="T"|`TotalP flag`=="T,J"|`TotalP flag`=="T, J"|`TotalP flag`=="T,Y"|`TotalP flag`=="T, Y" , NA),
         `TKN (mg/L)` = replace(`TKN (mg/L)`, `TKN flag`=="T"|`TKN flag`=="T,J"|`TKN flag`=="T, J"|`TKN flag`=="T,Y"|`TKN flag`=="T, Y" , NA))

summary_all_nutrients<-nutrients_year_filtered %>% 
  filter(Location=="St. Joseph Sound"|Location=="Piney Point"|Location=="Joe Bay"|Location=="Bishop Harbor"|Location=="Piney Point Facility") %>% #don't use effluent values, not certified samples, all other samples certified and values are used
  separate(`Date of Sample collection`, into=c("Year", "Month", "Day")) %>% 
  select(SampleID, Location, Year, Month, `NH4N (mg/L)`, `NOx (mg/L)`, `OrthoP (ug/L)`, 
         `TotalP (ug/L)`, `TKN (mg/L)`) %>% 
  group_by(Location, Year, Month) %>% 
  summarise_all(list(mean=mean, sd=sd, min=min, max=max), na.rm=TRUE) %>% 
  select_if(!grepl("SampleID", names(.))) %>% 
  unique()

write.csv(summary_all_nutrients, "2023_01_10_nutrient_data_summarized.csv")

```