---
title: "Sonde data: Piney Point 1 year"
output:
  pdf_document: default
  html_document: default
  word_document: default
---




```{r setup, include=FALSE, echo=FALSE}

 # Consolidating sonde data

library(tidyverse)
library(readxl)
library(lubridate)
library(cowplot)
library(ggtext)

```


```{r, include=FALSE, echo=FALSE}
#### recursive search for .csv under top level directory

# top level directory: 
top_dir<-"C:/Users/emorrison/Dropbox (UFL)/Tampa/PineyPoint/PineyPoint_RAPID_shared/Data/Sonde data/April2021_to_May2022"


file_list<-list.files(path=top_dir, recursive = TRUE, pattern=("*.csv"))

#### check file name for consistent site name
#### 2021-04-16_2021-04-29_PineyPoint_sonde1_StJosephSound_YSI4a_20A102230_UF_Norby

#loop over list of file names

firstfile<-TRUE

for (filenamedir in file_list){
  print("----------------------------------------------")
  print(paste0("    ", filenamedir))
  
  #extract the file name for each .csv
  file_name<-str_split(string = filenamedir, pattern="/")[[1]][2]
  ##take first element of list [[1]], second string [2]
  
  #extract the site name from file name
  # site name is 5th block with _ delimiter
  site_name<-str_split(string=file_name, pattern="_")[[1]][5]
  
  print(paste0("               ", site_name))
  
  filedata<-tibble(read_csv(paste0(top_dir, "/", filenamedir), skip=8, local = locale(encoding = "latin1"), show_col_types = FALSE)) %>% #remove top 8 rows
    rename("Project" = "Site Name") %>%  #Project ID included as site name in original file
    select(-'Time (Fract. Sec)') %>% 
    mutate("Site_ID" = site_name,
           "Date_ymd" = as_date(mdy(`Date (MM/DD/YYYY)`)), 
           "Time_hms" = hms(`Time (HH:mm:ss)`))
  
  if(firstfile==TRUE){
    agglomerateddata <- filedata
    firstfile <- FALSE
  }
  else{
    agglomerateddata<-bind_rows(agglomerateddata, filedata)
  }
  
  print(nrow(agglomerateddata))
  
  print(paste0(" ======================== ", site_name, "     done"))
  
}


## If there are additional headers, there will be an error
## use this to check what Date_ymd were NA values to troubleshoot

NA_agglomerated<-filter(agglomerateddata, is.na(Date_ymd))


```


```{r, include=FALSE, echo=FALSE}
#Piney Point Sonde was called CockRoach Bay, other sites don't have space in names, correct names
agglomerateddata$Site_ID<-gsub("CockroachBay", "Piney Point", agglomerateddata$Site_ID)
agglomerateddata$Site_ID<-gsub("BishopHarbor", "Bishop Harbor", agglomerateddata$Site_ID)
agglomerateddata$Site_ID<-gsub("JoeBay", "Joe Bay", agglomerateddata$Site_ID)
agglomerateddata$Site_ID<-gsub("StJosephSound", "St. Joseph Sound", agglomerateddata$Site_ID)



#filter each variable to the range of the sensor, reported in Exo2 manual

trimmed<-agglomerateddata %>% 
  mutate(`Chlorophyll RFU` = replace(`Chlorophyll RFU`, `Chlorophyll RFU`>100 | `Chlorophyll RFU`<0, NA), 
         `Chlorophyll ug/L` = replace(`Chlorophyll ug/L`, `Chlorophyll ug/L`>400 | `Chlorophyll ug/L`<0, NA),
         `fDOM RFU` = replace(`fDOM RFU`, `fDOM RFU`<0 | `fDOM RFU` >100, NA), 
         `ODO % sat` = replace(`ODO % sat`, `ODO % sat`<0  | `ODO % sat`>500, NA),
         `ODO mg/L` = replace(`ODO mg/L`, `ODO mg/L`<0  | `ODO mg/L`>20, NA), #a few anomalously high values in SSJS
         `SpCond µS/cm` = replace(`SpCond µS/cm`, `SpCond µS/cm`<0  | `SpCond µS/cm`>200, NA),                      
         `BGA PE RFU` = replace(`BGA PE RFU`, `BGA PE RFU`<0  | `BGA PE RFU`>40, NA), #had anomalously high values in Feb/March, likely issue with sensor
         `BGA PE ug/L` = replace(`BGA PE ug/L`, `BGA PE ug/L`<0  | `BGA PE ug/L`>280, NA),                   
         `Turbidity FNU` = replace(`Turbidity FNU`, `Turbidity FNU`<0  | `Turbidity FNU`>4000, NA), 
         `Temp °C` = replace(`Temp °C`, `Temp °C`<5  | `Temp °C`>50, NA),
         `pH` = replace(`pH`, `pH`<0  | `pH`>14, NA),
         `Sal psu` = replace(`Sal psu`, `pH`<0  | `Sal psu`>35, NA),
         `ORP mV` = replace(`ORP mV`, `ORP mV`<-999  | `ORP mV`>999, NA))

#### generate summary statistics for all columns
summary_all_data<-trimmed %>% 
  group_by(Site_ID, Date_ymd) %>% 
  summarise_all(list(mean=mean, sd=sd, min=min, max=max), na.rm=TRUE)

write.csv(summary_all_data, "SondeOutput/2022_12_19_sonde_data_agglomerated_summarized.csv")

```

```{r, include=FALSE, echo=FALSE}
#Include fDOM and turbidity as supplementary figures
fDOM<-ggplot(summary_all_data, aes(`Date_ymd`, `fDOM RFU_mean`))+
  geom_point()+
  geom_smooth(se=FALSE, span=0.175)+
  facet_wrap(.~Site_ID)+
  theme_cowplot(font_size = 8)+
  panel_border(color="black")+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+
  geom_vline(xintercept = as.Date("2021-04-07"), linetype=4, color="red")+
  theme(text = element_text(size = 14), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1))+
  ylab("fDOM (RFU)")+
  xlab("")+
  geom_vline(xintercept = as.numeric(as.POSIXct(as.Date("2021-04-09"))), linetype=4, color="green")+ #date of effluent collection
  geom_rect(aes(ymin=-30, ymax=-13, xmin=as.POSIXct(as.Date("2021-03-30")), xmax=as.POSIXct(as.Date("2021-04-09"))), color="#00BA38", fill="#00BA38", alpha=0.01)+
  geom_rect(aes(ymin=-30, ymax=-13, xmin=as.POSIXct(as.Date("2021-06-13")), xmax=as.POSIXct(as.Date("2021-07-18"))), color="red", fill="red", alpha=0.01)+ #week of Jun 13 to July 18th reported as "high" k brevis from Beck et al., 2022, use dates

turb<-ggplot(summary_all_data, aes(`Date_ymd`, `Turbidity FNU_mean`))+
  geom_point()+
  geom_smooth(se=FALSE, span=0.175)+
  facet_wrap(.~Site_ID)+
  theme_cowplot(font_size = 8)+
  panel_border(color="black")+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+
  geom_vline(xintercept = as.Date("2021-04-07"), linetype=4, color="red")+
  theme(text = element_text(size = 14), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1))+
  ylab("Turbidity (FNU)")+
  xlab("")

supp_sonde_plot<-plot_grid(fDOM, turb, labels = c("A", "B"))
```

```{r, include=FALSE, echo=FALSE}
sal<-ggplot(summary_all_data, aes(`Date_ymd`, `Sal psu_mean`))+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.002)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.002)+
  geom_point()+
  geom_smooth(se=FALSE)+
  facet_wrap(.~Site_ID)+
  theme_cowplot(font_size = 8)+
  panel_border(color="black")+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+
  theme(text = element_text(size = 12), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1))+
  ylab("Salinity (psu)")+
  xlab("")


ODO_mg_L<-ggplot(summary_all_data, aes(`Date_ymd`, `ODO mg/L_mean`))+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.002)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.002)+
  geom_point()+
  geom_smooth(se=FALSE)+
  facet_wrap(.~Site_ID, scales="free_y")+
  theme_cowplot(font_size = 8)+
  panel_border(color="black")+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+
  theme(text = element_text(size = 12), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1))+
  ylab("Dissolved oxygen (mg/L)")+
  xlab("")

chl_ugL<-ggplot(summary_all_data, aes(`Date_ymd`, `Chlorophyll ug/L_mean`))+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.002)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.002)+
  geom_point()+
  geom_smooth(se=FALSE)+
  facet_wrap(.~Site_ID, scales="free_y")+
  theme_cowplot(font_size = 8)+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+
  panel_border(color="black")+
  theme(text = element_text(size = 12), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1))+
  ylab("In situ chlorophyll (ug/L)")+
  xlab("")

PE_ugL<-ggplot(summary_all_data, aes(`Date_ymd`, `BGA PE ug/L_mean`))+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-03-30"), xmax=as.Date("2021-04-09")), fill="#00BA38", alpha=0.002)+
  geom_rect(aes(ymin=-Inf, ymax=Inf, xmin=as.Date("2021-06-13"), xmax=as.Date("2021-07-18")), fill="red", alpha=0.002)+
  geom_point()+
  geom_smooth(se=FALSE)+
  facet_wrap(.~Site_ID, scales="free_y")+
  theme_cowplot(font_size = 8)+
  panel_border(color="black")+
  geom_vline(xintercept = as.Date("2021-07-05"), linetype=4, color="black")+
  theme(text = element_text(size = 12), 
        axis.text = element_text(size = 9), 
        axis.text.x = element_text(angle = -45, hjust = 0.1, vjust = 0.1))+
  ylab("Phycoerythrin (ug/L)")+
  xlab("")

sonde_plot<-plot_grid(sal, ODO_mg_L, chl_ugL, PE_ugL, labels = c("A", "B", "C", "D"))

ggsave("./Figures/2022_12_16_sonde_plot.png", sonde_plot)
```